name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9.12"
          architecture: "x64"
          cache: "pip"
          cache-dependency-path: settings.ini
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -qe ".[dev]"
          pip install -Uq git+https://github.com/fastai/fastcore.git
          pip install -Uq git+https://github.com/fastai/ghapi.git
      - name: Set git info for tests
        run: |
          git config --global user.email "${GH_EMAIL}"
          git config --global user.name "${GH_USERNAME}"
      - name: Check if all notebooks are cleaned
        run: |
          echo "Check we are starting with clean git checkout"
          if [ -n "$(git status -uno -s)" ]; then echo "git status is not clean"; false; fi
          echo "Trying to strip out notebooks"
          nbprocess_clean
          echo "Check that strip out was unnecessary"
          git status -s # display the status to see which nbs need cleaning up
          if [ -n "$(git status -uno -s)" ]; then echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbprocess_install_hooks"; false; fi
      - name: Test Notebooks
        run: nbprocess_test
